"""Authoritative Internal AAGAM Knowledge Layer (PRD §9, §12).

Provides structured, canon-grounded definitions, formulas, workflows, and UI explanations
for the 60 canonical topics of the AAGAM (Adaptive AI-Grid Assimilation Model) system.

Guiding Principles:
1. CONCEPTUAL GROUNDING: Defines metrics, UI controls, architectures, and terminology.
2. DYNAMIC VALUE PROHIBITION: Never hard-codes operational runtime values (e.g. current
   temperature, active alerts, live weights, current dates, or active model version string).
   Runtime figures MUST be queried via live tools.
3. STRICT TERMINOLOGY: Uses exact NCMRWF / IMD / MoES meteorology domain standards.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class KnowledgeEntry:
    id: str
    topic: str
    category: str
    explanation: str
    formula: Optional[str] = None
    allowed_terms: tuple[str, ...] = ()
    source_ref: str = ""
    is_dynamic: bool = False
    keywords: tuple[str, ...] = ()


AAGAM_KNOWLEDGE_BASE: Dict[str, KnowledgeEntry] = {
    # 1. Identity & Purpose
    "app_identity": KnowledgeEntry(
        id="app_identity",
        topic="Application Identity",
        category="Identity",
        explanation="AAGAM stands for Adaptive AI-Grid Assimilation Model. It is an operational decision-support forecasting platform built for Indian regional weather resilience.",
        allowed_terms=("AAGAM", "Adaptive AI-Grid Assimilation Model"),
        source_ref="PRD §1",
        keywords=("aagam", "identity", "what is aagam", "who are you", "system"),
    ),
    "core_purpose": KnowledgeEntry(
        id="core_purpose",
        topic="Core Purpose",
        category="Identity",
        explanation="AAGAM synthesizes multi-model Numerical Weather Prediction (NWP) forecasts into an adaptive machine-learning consensus to provide high-resolution decision support for extreme weather events across India.",
        allowed_terms=("decision support", "multi-model consensus", "NWP assimilation"),
        source_ref="PRD §1, §2",
        keywords=("purpose", "goal", "objective", "why aagam", "mission"),
    ),
    "forecast_variables": KnowledgeEntry(
        id="forecast_variables",
        topic="Forecast Variables",
        category="Meteorology",
        explanation="AAGAM tracks three primary operational meteorological variables: 24-hour accumulated rainfall (rain_mm), maximum daily 2m temperature (tmax_c), and peak 10m wind speed / gust (wind_max_kmh).",
        allowed_terms=("rain_mm", "tmax_c", "wind_max_kmh", "rainfall", "maximum temperature", "peak wind"),
        source_ref="PRD §5, §12",
        keywords=("variables", "weather parameters", "rain_mm", "tmax_c", "wind_max_kmh", "track"),
    ),
    "units": KnowledgeEntry(
        id="units",
        topic="Units of Measurement",
        category="Meteorology",
        explanation="Authoritative measurement units are: Rainfall in mm/24h (ending 08:30 IST), Maximum Temperature in °C (Celsius), and Peak Wind in km/h (kilometers per hour).",
        allowed_terms=("mm/24h", "°C", "km/h"),
        source_ref="PRD §5.1, §12",
        keywords=("units", "measurement", "metric unit", "celsius", "km/h", "mm/24h"),
    ),
    "four_nwp_models": KnowledgeEntry(
        id="four_nwp_models",
        topic="Four NWP Models",
        category="Modeling",
        explanation="AAGAM ingests four authoritative Numerical Weather Prediction models: GFS (NOAA Global Forecast System, 0.25°), ECMWF IFS (European Centre for Medium-Range Weather Forecasts Integrated Forecasting System, 0.25°), DWD ICON (Deutscher Wetterdienst Icosahedral Nonhydrostatic model, 0.25°), and ECMWF AIFS (AI-driven Integrated Forecasting System, 0.25°).",
        allowed_terms=("GFS", "ECMWF IFS", "DWD ICON", "ECMWF AIFS", "NWP"),
        source_ref="PRD §7.1, Tech Stack §3",
        keywords=("models", "gfs", "ecmwf", "ifs", "icon", "aifs", "nwp models", "four models"),
    ),
    "aagam_blend": KnowledgeEntry(
        id="aagam_blend",
        topic="AAGAM Blend",
        category="Modeling",
        explanation="The AAGAM Blend is an adaptive composite forecast generated by ML engines (Ridge stacking regression and LightGBM) trained on rolling hindcasts. When ML weights degrade or lack samples, it gracefully falls back to hierarchical Inverse-MAE weighting.",
        formula="y_blend = sum(w_i * m_i) where sum(w_i) = 1.0",
        allowed_terms=("AAGAM Blend", "Adaptive Blend", "ensemble consensus", "Ridge stacking"),
        source_ref="PRD §7.2, §8.1",
        keywords=("blend", "aagam blend", "blended", "how blend works", "stacking"),
    ),
    "lead_days": KnowledgeEntry(
        id="lead_days",
        topic="Lead Days Horizon",
        category="Meteorology",
        explanation="AAGAM forecasts operate over an 8-day operational horizon from D0 (current day / Day 0) through D7 (Day +7). D0 represents current valid day conditions, D+1 is tomorrow, and D+7 is 7 days ahead.",
        allowed_terms=("D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "lead days", "forecast horizon"),
        source_ref="PRD §5.1, §10.1",
        keywords=("lead", "lead days", "d+1", "d+2", "d+3", "d+4", "d+7", "d0", "horizon"),
    ),
    "model_spread": KnowledgeEntry(
        id="model_spread",
        topic="Model Spread (Uncertainty)",
        category="Meteorology",
        explanation="Model spread represents the divergence or range among the four constituent NWP models for a specific valid date and location. Higher spread indicates lower inter-model agreement and elevated forecast uncertainty.",
        formula="Spread = max(model_i) - min(model_i)",
        allowed_terms=("spread", "model spread", "sigma", "ensemble dispersion", "divergence"),
        source_ref="PRD §8.3",
        keywords=("spread", "model spread", "uncertainty", "dispersion", "divergence"),
    ),
    "models_over_threshold": KnowledgeEntry(
        id="models_over_threshold",
        topic="Models Over Threshold",
        category="Alerts",
        explanation="Models Over Threshold (0 to 4) indicates how many of the 4 NWP models simultaneously forecast values exceeding an IMD hazard threshold (e.g., rainfall >= 64.5 mm/24h). A 3/4 or 4/4 count signals high multi-model consensus.",
        allowed_terms=("models over threshold", "model consensus", "exceedance count"),
        source_ref="PRD §8.2, §10.2",
        keywords=("models over threshold", "threshold count", "consensus", "exceedance"),
    ),
    "weight_maps": KnowledgeEntry(
        id="weight_maps",
        topic="Weight Maps",
        category="Modeling",
        explanation="Weight Maps in the UI visualize the geographical and lead-dependent contribution of each NWP model across India's meteorological regions (NORTH, SOUTH, EAST_NE, WEST, CENTRAL).",
        allowed_terms=("Weight Maps", "regional weights", "spatial weights"),
        source_ref="PRD §10.3",
        keywords=("weight maps", "weights map", "regional weights", "weight page"),
    ),
    "model_weights": KnowledgeEntry(
        id="model_weights",
        topic="Model Weights",
        category="Modeling",
        explanation="Model weights are normalized fractions (summing to 1.0) assigned to each of the 4 models based on recent verification skill in that region, season, and lead time. Better-performing models receive higher weights.",
        formula="w_i = (1 / MAE_i) / sum(1 / MAE_j)",
        allowed_terms=("model weights", "contribution weights", "inverse-MAE weights"),
        source_ref="PRD §7.3",
        keywords=("weights", "model weight", "how weights calculated", "weight calculation"),
    ),
    "dominant_model": KnowledgeEntry(
        id="dominant_model",
        topic="Dominant Model",
        category="Modeling",
        explanation="The dominant model is the constituent NWP model that has been assigned the largest relative blending weight for a given region, season, and lead day slice.",
        allowed_terms=("dominant model", "primary model", "highest weight"),
        source_ref="PRD §10.3",
        keywords=("dominant", "dominant model", "highest weight", "primary model"),
    ),
    "weight_override": KnowledgeEntry(
        id="weight_override",
        topic="Weight Override",
        category="Governance",
        explanation="Weight Overrides allow authorized Forecasters or Coordinators to temporarily adjust model weights for a specific region, lead day, and variable during unusual synoptic conditions. Overrides require a mandatory audit reason and expire automatically within 72 hours.",
        allowed_terms=("weight override", "manual override", "expert intervention"),
        source_ref="PRD §11.2, §12",
        keywords=("override", "weight override", "manual override", "adjust weights"),
    ),

    # 2. Skill & Verification
    "skill_verification": KnowledgeEntry(
        id="skill_verification",
        topic="Skill & Verification",
        category="Verification",
        explanation="Skill & Verification evaluates how accurately past forecasts predicted actual verified ground truth observations. The Skill page reports continuous error metrics (MAE, RMSE, Bias) and categorical hazard detection metrics (POD, FAR, CSI).",
        allowed_terms=("Skill page", "verification", "forecast skill", "forecast evaluation"),
        source_ref="PRD §6, §12",
        keywords=("skill", "verification", "accuracy", "performance", "skill page"),
    ),
    "verification_dataset": KnowledgeEntry(
        id="verification_dataset",
        topic="Verification Dataset",
        category="Verification",
        explanation="The verification dataset is formed by pairing historical forecasts against actual ground truth recorded on that valid date at the exact same location coordinates, accounting for observation cutoffs.",
        allowed_terms=("verification dataset", "forecast-truth pairs", "evaluation data"),
        source_ref="PRD §6.1",
        keywords=("verification dataset", "verification data", "evaluation dataset"),
    ),
    "mae": KnowledgeEntry(
        id="mae",
        topic="Mean Absolute Error (MAE)",
        category="Verification",
        explanation="MAE measures the average magnitude of forecast errors without considering their direction. Lower MAE values indicate superior forecast accuracy.",
        formula="MAE = (1 / N) * sum(|Forecast_i - Observed_i|)",
        allowed_terms=("MAE", "Mean Absolute Error"),
        source_ref="PRD §6.2",
        keywords=("mae", "mean absolute error", "what is mae", "how mae calculated"),
    ),
    "rmse": KnowledgeEntry(
        id="rmse",
        topic="Root Mean Squared Error (RMSE)",
        category="Verification",
        explanation="RMSE measures the square root of the mean squared differences between forecasts and observations. Because errors are squared before averaging, RMSE penalizes large forecast outliers more heavily than MAE.",
        formula="RMSE = sqrt((1 / N) * sum((Forecast_i - Observed_i)^2))",
        allowed_terms=("RMSE", "Root Mean Squared Error"),
        source_ref="PRD §6.2",
        keywords=("rmse", "root mean squared error", "what is rmse", "how rmse calculated"),
    ),
    "bias": KnowledgeEntry(
        id="bias",
        topic="Forecast Bias (Mean Error)",
        category="Verification",
        explanation="Bias measures the mean systematic directional tendency of the forecast. A positive bias means the model systematically over-forecasts; a negative bias means it under-forecasts. Zero bias represents an unbiased forecast.",
        formula="Bias = (1 / N) * sum(Forecast_i - Observed_i)",
        allowed_terms=("Bias", "Mean Error", "systematic bias"),
        source_ref="PRD §6.2",
        keywords=("bias", "forecast bias", "mean error", "what is bias"),
    ),
    "pod": KnowledgeEntry(
        id="pod",
        topic="Probability of Detection (POD)",
        category="Verification",
        explanation="POD (Hit Rate) measures the fraction of observed extreme weather events that were correctly forecasted by the model. Values range from 0 to 1 (or 0% to 100%), where 1 indicates perfect detection.",
        formula="POD = Hits / (Hits + Misses)",
        allowed_terms=("POD", "Probability of Detection", "Hit Rate"),
        source_ref="PRD §6.3",
        keywords=("pod", "probability of detection", "hit rate", "what is pod"),
    ),
    "far": KnowledgeEntry(
        id="far",
        topic="False Alarm Ratio (FAR)",
        category="Verification",
        explanation="FAR measures the proportion of forecasted extreme weather events that did not actually materialize in observed truth. Values range from 0 to 1, where 0 indicates zero false alarms.",
        formula="FAR = False_Alarms / (Hits + False_Alarms)",
        allowed_terms=("FAR", "False Alarm Ratio"),
        source_ref="PRD §6.3",
        keywords=("far", "false alarm ratio", "false alarm rate", "what is far"),
    ),
    "csi": KnowledgeEntry(
        id="csi",
        topic="Critical Success Index (CSI / Threat Score)",
        category="Verification",
        explanation="CSI (also known as Threat Score) measures the overall accuracy of extreme event forecasting by balancing hits against both misses and false alarms. It disregards correct negative non-events.",
        formula="CSI = Hits / (Hits + Misses + False_Alarms)",
        allowed_terms=("CSI", "Critical Success Index", "Threat Score"),
        source_ref="PRD §6.3",
        keywords=("csi", "critical success index", "threat score", "what is csi"),
    ),
    "heavy_rain_contingency": KnowledgeEntry(
        id="heavy_rain_contingency",
        topic="Heavy-Rain Contingency Metrics",
        category="Verification",
        explanation="Contingency metrics (POD, FAR, CSI) are evaluated against 2x2 confusion matrices (Hits, Misses, False Alarms, Correct Negatives) at standard IMD rainfall thresholds: 64.5 mm (Heavy Rain), 115.6 mm (Very Heavy Rain), and 204.5 mm (Extremely Heavy Rain).",
        allowed_terms=("contingency metrics", "confusion matrix", "hazard thresholds"),
        source_ref="PRD §6.3, §8.2",
        keywords=("contingency", "confusion matrix", "heavy rain verification", "contingency table"),
    ),
    "live_verification": KnowledgeEntry(
        id="live_verification",
        topic="Live Verification",
        category="Verification",
        explanation="Live Verification measures the active operational accuracy of AAGAM forecasts against real-time verified observations over a dynamic rolling window (min(actual verified days, 90 days)). It reflects current operational performance.",
        allowed_terms=("Live Verification", "operational verification", "trailing skill"),
        source_ref="PRD §6.4",
        keywords=("live verification", "live skill", "operational skill", "dynamic window"),
    ),
    "held_out_90_day_test": KnowledgeEntry(
        id="held_out_90_day_test",
        topic="Formal Held-Out 90-Day Test Benchmark",
        category="Verification",
        explanation="The Held-Out 90-Day Test is AAGAM's formal scientific benchmark block spanning exactly 2026-06-21 through 2026-09-18 (the 2026 South Asian Monsoon). It is a fixed, non-leaking test partition evaluated once to baseline model capability.",
        allowed_terms=("Held-Out 90-Day Test", "benchmark", "held-out test block", "formal test"),
        source_ref="PRD §7.4",
        keywords=("held-out", "held out", "benchmark", "90-day test", "held out benchmark", "2026-06-21"),
    ),
    "verification_maturity": KnowledgeEntry(
        id="verification_maturity",
        topic="Verification Maturity States",
        category="Verification",
        explanation="Live verification progresses through standardized maturity tiers as verified daily observations accumulate: PRELIMINARY (1-3 days), EARLY (4-6 days), LIVE VERIFICATION (7-89 days), and LIVE VERIFICATION · 90-DAY MAX (90 days).",
        allowed_terms=("PRELIMINARY", "EARLY", "LIVE VERIFICATION", "maturity tiers"),
        source_ref="PRD §6.4",
        keywords=("maturity", "preliminary", "early verification", "maturity states", "why preliminary"),
    ),
    "truth_sources": KnowledgeEntry(
        id="truth_sources",
        topic="Observation Truth Sources",
        category="Data",
        explanation="Authoritative daily observation truth is ingested from IMD 0.25° gridded daily rainfall data (National Data Centre, Pune). When the IMD feed is offline, the pipeline automatically falls back to ERA5 reanalysis and climatology.",
        allowed_terms=("IMD 0.25° gridded", "ERA5 reanalysis", "ground truth"),
        source_ref="PRD §5.2, §12",
        keywords=("truth", "truth sources", "where truth comes from", "imd truth", "era5 truth"),
    ),
    "imd_fallback": KnowledgeEntry(
        id="imd_fallback",
        topic="IMD Offline Fallback Behavior",
        category="Data",
        explanation="If the official IMD gridded observation pipeline is unavailable or delayed, AAGAM automatically transitions to ERA5 Climatology Fallback. The UI and verification endpoints clearly flag this degraded state as 'ERA5 Climatology Fallback (IMD Offline)'.",
        allowed_terms=("ERA5 Climatology Fallback", "IMD Offline", "truth fallback"),
        source_ref="PRD §5.2, §6.5",
        keywords=("fallback", "imd offline", "truth fallback", "era5 fallback"),
    ),

    # 3. Extremes & Hazards
    "extreme_weather_center": KnowledgeEntry(
        id="extreme_weather_center",
        topic="Extreme Weather Center",
        category="Alerts",
        explanation="The Extreme Weather Center is AAGAM's operational dashboard for tracking active hazardous weather events (heavy rainfall, heatwaves, high wind, and model uncertainty) across India with severity filtering and acknowledgement tracking.",
        allowed_terms=("Extreme Weather Center", "alert center", "hazard dashboard"),
        source_ref="PRD §10.2",
        keywords=("extreme weather center", "alerts page", "hazard center", "extreme weather"),
    ),
    "heavy_rain_hazard": KnowledgeEntry(
        id="heavy_rain_hazard",
        topic="Heavy Rain Hazard (64.5 mm)",
        category="Alerts",
        explanation="Heavy rain warnings trigger at IMD standard thresholds: >= 64.5 mm/24h represents Heavy Rain (Alert), >= 115.6 mm represents Very Heavy Rain, and >= 204.5 mm represents Extremely Heavy Rain.",
        allowed_terms=("Heavy Rain", "64.5 mm", "115.6 mm", "204.5 mm"),
        source_ref="PRD §8.2",
        keywords=("heavy rain", "64.5 mm", "rainfall alert", "rain threshold"),
    ),
    "heatwave_hazard": KnowledgeEntry(
        id="heatwave_hazard",
        topic="Heatwave Hazard (40.0°C / 45.0°C)",
        category="Alerts",
        explanation="Heatwave alerts activate based on maximum temperature (tmax_c): >= 40.0°C initiates a Heatwave Watch (plains criteria), and >= 45.0°C triggers a Severe Heatwave Alert.",
        allowed_terms=("Heatwave", "Heatwave Watch", "Severe Heatwave", "40°C", "45°C"),
        source_ref="PRD §8.2",
        keywords=("heatwave", "heat wave", "40c", "45c", "heat threshold", "tmax alert"),
    ),
    "high_wind_hazard": KnowledgeEntry(
        id="high_wind_hazard",
        topic="High Wind / Gale Hazard (62 km/h)",
        category="Alerts",
        explanation="Wind alerts trigger when peak 10m wind speed or gusts reach gale force: >= 62.0 km/h triggers a Gale Wind advisory/watch, and >= 75.0 km/h triggers a Strong Gale warning.",
        allowed_terms=("Gale Wind", "Strong Gale", "high wind", "62 km/h", "75 km/h"),
        source_ref="PRD §8.2",
        keywords=("wind", "high wind", "gale", "62 km/h", "wind threshold"),
    ),
    "high_uncertainty": KnowledgeEntry(
        id="high_uncertainty",
        topic="High Uncertainty Condition",
        category="Alerts",
        explanation="A High Uncertainty advisory is raised when NWP models show extreme dispersion (spread >= 30 mm/24h or 5.0°C) or when exactly 2 of 4 models predict a severe hazard while the other 2 predict normal conditions.",
        allowed_terms=("High Uncertainty", "model divergence", "split consensus"),
        source_ref="PRD §8.2, §10.2",
        keywords=("high uncertainty", "uncertainty", "what does high uncertainty mean", "split consensus"),
    ),
    "severity_levels": KnowledgeEntry(
        id="severity_levels",
        topic="Alert Severity Levels",
        category="Alerts",
        explanation="AAGAM categorizes alerts into three operational severity tiers: Advisory (low/watchful), Watch (moderate confidence / prep), and Alert (high confidence or severe threshold exceedance).",
        allowed_terms=("Advisory", "Watch", "Alert", "Severity"),
        source_ref="PRD §8.2",
        keywords=("severity", "severity levels", "advisory", "watch", "alert"),
    ),
    "model_agreement": KnowledgeEntry(
        id="model_agreement",
        topic="Model Agreement",
        category="Alerts",
        explanation="Model agreement reflects consensus among the 4 NWP models regarding an impending hazard, typically expressed as 'X/4 models exceed threshold'. High agreement (3/4 or 4/4) strengthens forecaster confidence.",
        allowed_terms=("model agreement", "consensus", "agreement chip"),
        source_ref="PRD §8.2, §10.2",
        keywords=("agreement", "model agreement", "consensus", "how many models agree"),
    ),
    "alert_acknowledgement": KnowledgeEntry(
        id="alert_acknowledgement",
        topic="Alert Acknowledgement",
        category="Governance",
        explanation="Forecasters and Coordinators can acknowledge active alert events using a 2-step confirmation modal in the UI. Acknowledgement records the user ID, timestamp, and notes into the audit trail while keeping the event visible in acknowledged state.",
        allowed_terms=("acknowledge", "alert acknowledgement", "ack confirmation"),
        source_ref="PRD §10.2, §11.1",
        keywords=("acknowledge", "how to acknowledge", "acknowledging alert", "ack"),
    ),
    "alert_cancellation": KnowledgeEntry(
        id="alert_cancellation",
        topic="Cancelled by Forecaster",
        category="Governance",
        explanation="'Cancelled by Forecaster' indicates an active alert event was manually terminated by an authorized forecaster who determined the synoptic threat has passed or was a false alarm. It requires an audit reason and transitions status to 'cancelled'.",
        allowed_terms=("Cancelled by Forecaster", "alert cancellation", "dismissed alert"),
        source_ref="PRD §10.2, §11.1",
        keywords=("cancelled", "cancelled by forecaster", "cancel alert", "why cancelled"),
    ),

    # 4. Data & Pipeline
    "forecast_history": KnowledgeEntry(
        id="forecast_history",
        topic="Forecast History",
        category="Data",
        explanation="Forecast History enables retrospective querying of previous model forecasts and observed ground truth over arbitrary date ranges up to a 5,000-row pagination safety boundary.",
        allowed_terms=("Forecast History", "retrospective query", "historical archive"),
        source_ref="PRD §10.5",
        keywords=("history", "forecast history", "past forecasts", "query history"),
    ),
    "data_export": KnowledgeEntry(
        id="data_export",
        topic="Data & Signed Export",
        category="Data",
        explanation="AAGAM provides secure bulk data exports for forecasts, history, skill scores, weights, and alerts in CSV and JSON formats via HMAC-signed, 10-minute download URLs generated by the backend.",
        allowed_terms=("data export", "signed URL", "bulk download", "CSV export"),
        source_ref="PRD §12",
        keywords=("export", "data export", "download data", "csv export", "json export"),
    ),
    "pipeline_health": KnowledgeEntry(
        id="pipeline_health",
        topic="Pipeline Health",
        category="Operations",
        explanation="Pipeline Health displays the execution telemetry, status, row counts, API rate-limit utilization, and run duration for scheduled backend jobs (ingest-blend, verify-daily, truth_ingestion, and retention_cleanup) running on a daily scheduled cadence.",
        allowed_terms=("Pipeline Health", "telemetry", "pipeline runs", "job status", "daily cadence"),
        source_ref="PRD §10.6, §11.3",
        keywords=("pipeline health", "pipeline", "jobs", "ingest-blend", "job status", "daily pipeline schedule", "cadence", "daily pipeline", "schedule and cadence", "pipeline schedule"),
    ),
    "degraded_state": KnowledgeEntry(
        id="degraded_state",
        topic="Degraded State",
        category="Operations",
        explanation="'Degraded' signals that one or more upstream NWP models were missing or delayed during ingestion, or that the ML stacking engine fell back to inverse-MAE weighting. When a model is missing, its value remains null (never substituted with the blend).",
        allowed_terms=("degraded", "degraded mode", "fallback blend", "missing model", "null model"),
        source_ref="PRD §8.4",
        keywords=("degraded", "what does degraded mean", "degraded state", "missing model", "what happens when a model is missing", "model is missing", "model missing", "null instead of blend", "why null instead of blend", "model values null"),
    ),

    # 5. Assistant & UI Features
    "assistant_modes": KnowledgeEntry(
        id="assistant_modes",
        topic="Assistant Modes (Explain, Raw, Both)",
        category="Assistant",
        explanation="AAGAM Assistant operates in three user-selectable modes: EXPLAIN provides concise 2-5 sentence meteorological commentary; RAW renders data tables with at most a 1-sentence caption; BOTH provides both the data table and analytical narrative.",
        allowed_terms=("EXPLAIN mode", "RAW mode", "BOTH mode", "assistant modes"),
        source_ref="PRD §9.2, §10.4",
        keywords=("modes", "raw mode", "explain mode", "both mode", "assistant modes"),
    ),
    "tool_data_tables": KnowledgeEntry(
        id="tool_data_tables",
        topic="Interactive Data Tables",
        category="Assistant",
        explanation="Data tables in the Assistant chat are rendered directly in the browser UI from structured backend tool payloads (via Server-Sent Events). Raw numerical data is never dumped into markdown text.",
        allowed_terms=("data table", "interactive table", "data_table event"),
        source_ref="PRD §9.3, §10.4",
        keywords=("data table", "table in assistant", "raw table"),
    ),
    "artifacts": KnowledgeEntry(
        id="artifacts",
        topic="Assistant Artifacts",
        category="Assistant",
        explanation="Artifacts are structured datasets (forecast tables, skill matrices, export links) generated during tool execution and stored server-side with unique IDs, allowing persistent referencing and one-click CSV copying.",
        allowed_terms=("artifact", "artifact_id", "tool artifact"),
        source_ref="PRD §9.4, §12",
        keywords=("artifact", "artifacts", "what is artifact"),
    ),
    "cache": KnowledgeEntry(
        id="cache",
        topic="Assistant Response Cache",
        category="Assistant",
        explanation="The Assistant incorporates a 10-minute deterministic response cache keyed by user query, active model version, and mode to reduce LLM token usage and deliver instantaneous responses for repeated questions.",
        allowed_terms=("response cache", "10-minute cache", "cached response"),
        source_ref="PRD §9.3",
        keywords=("cache", "assistant cache", "response cache"),
    ),
    "rate_limiting": KnowledgeEntry(
        id="rate_limiting",
        topic="Assistant Rate Limiting",
        category="Assistant",
        explanation="Assistant queries are rate-limited to 15 questions per hour per user. If the limit is exceeded, the server returns an HTTP 429 error specifying the retry-after window in seconds.",
        allowed_terms=("rate limit", "15 questions per hour", "quota"),
        source_ref="PRD §9.3, §12",
        keywords=("rate limit", "rate limiting", "hourly quota", "too many requests"),
    ),
    "prompt_injection_protection": KnowledgeEntry(
        id="prompt_injection_protection",
        topic="Prompt Injection Protection",
        category="Security",
        explanation="AAGAM includes multi-layer defensive sanitization that inspects all inbound queries and tool payloads. Queries attempting to reveal system prompts, alter security rules, or execute unapproved actions are safely refused.",
        allowed_terms=("prompt injection", "security shield", "input sanitization"),
        source_ref="PRD §9.1",
        keywords=("prompt injection", "security", "jailbreak", "shield"),
    ),
    "forty_configured_locations": KnowledgeEntry(
        id="forty_configured_locations",
        topic="40 Configured Representative Locations",
        category="Meteorology",
        explanation="AAGAM monitors strictly 40 authoritative representative station locations across India (e.g., Kolkata, Bhubaneswar, Nagpur, Delhi, Mumbai, Chennai, Guwahati) chosen to cover all major agro-climatic zones and terrain types.",
        allowed_terms=("40 configured locations", "representative points", "authoritative stations"),
        source_ref="PRD §4.1, config/locations.yaml",
        keywords=("40 locations", "locations", "cities", "stations", "coverage"),
    ),

    # 6. Roles & RBAC
    "auth_roles": KnowledgeEntry(
        id="auth_roles",
        topic="Authentication & 3-Role RBAC",
        category="Security",
        explanation="AAGAM implements a strict 3-tier Role-Based Access Control model: Public (view forecasts, maps, skill, and ask Assistant), Forecaster (acknowledge alerts, cancel false alarms, request weight overrides), and Coordinator (approve forecasters, manage models, configure subscriptions).",
        allowed_terms=("Public", "Forecaster", "Coordinator", "RBAC"),
        source_ref="PRD §11.1",
        keywords=("roles", "rbac", "public", "forecaster", "coordinator", "permissions"),
    ),
    "forecaster_access_request": KnowledgeEntry(
        id="forecaster_access_request",
        topic="Forecaster Access Request",
        category="Security",
        explanation="Authenticated Public users can request promotion to Forecaster via the Settings page by submitting their departmental affiliation and operational justification.",
        allowed_terms=("forecaster request", "role upgrade", "access request"),
        source_ref="PRD §11.1",
        keywords=("request forecaster", "become forecaster", "forecaster access", "upgrade role"),
    ),
    "coordinator_governance": KnowledgeEntry(
        id="coordinator_governance",
        topic="Coordinator Governance & Approvals",
        category="Security",
        explanation="Coordinators have administrative oversight to approve or reject pending Forecaster role requests and promote active Forecasters to Coordinator in the Settings panel.",
        allowed_terms=("Coordinator approval", "role management", "coordinator governance"),
        source_ref="PRD §11.1",
        keywords=("coordinator", "approve forecaster", "promote coordinator", "governance"),
    ),
    "subscription_management": KnowledgeEntry(
        id="subscription_management",
        topic="Alert Subscriptions",
        category="Notifications",
        explanation="Users can configure automated email and SMS notifications in the 'Manage Alert Subscriptions' modal, specifying favorite locations, minimum severity thresholds, and notification frequency.",
        allowed_terms=("subscriptions", "alert notifications", "email alerts", "sms alerts"),
        source_ref="PRD §11.4",
        keywords=("subscriptions", "subscribe", "alert subscription", "notifications", "subscription management", "how do subscriptions work", "how subscriptions work", "unsubscribe"),
    ),
    "notification_types": KnowledgeEntry(
        id="notification_types",
        topic="Notification Types",
        category="Notifications",
        explanation="AAGAM supports automated notifications via Email, In-App / Browser alerts, and Webhooks for external dispatch. SMS notifications can be enabled via webhook integration.",
        allowed_terms=("Email alerts", "Browser Push", "Webhooks", "SMS alerts"),
        source_ref="PRD §11.4",
        keywords=("notification types", "notifications supported", "what notification types", "email", "browser", "webhook"),
    ),

    # 7. Model Versioning & Lifecycle
    "model_versions": KnowledgeEntry(
        id="model_versions",
        topic="Model Versions & Semantic Tagging",
        category="MLOps",
        explanation="Model versions represent trained machine-learning blending checkpoints (e.g., v2026-09-21) tracked in the database with training metrics, sample counts, and artifact paths.",
        allowed_terms=("model version", "version_id", "semantic version"),
        source_ref="PRD §11.2, MLOps Spec",
        keywords=("model version", "model versions", "versioning", "active model version", "what is the model version"),
    ),
    "model_lifecycle": KnowledgeEntry(
        id="model_lifecycle",
        topic="Model Lifecycle States",
        category="MLOps",
        explanation="Models transition through strict lifecycle states: candidate -> evaluation -> shadow -> canary -> active. Only one model version can be active at any given time.",
        allowed_terms=("candidate", "evaluation", "shadow", "canary", "active"),
        source_ref="MLOps Spec §2",
        keywords=("lifecycle", "shadow", "canary", "active model", "model lifecycle", "what are shadow and canary"),
    ),
    "automatic_model_switching": KnowledgeEntry(
        id="automatic_model_switching",
        topic="Automatic Model Switching",
        category="MLOps",
        explanation="Automatic model switching promotes a candidate shadow model to active only if it demonstrates statistically superior MAE over the incumbent active model across a 14-day rolling window by a defined safety margin.",
        allowed_terms=("automatic model switching", "promotion", "switch margin"),
        source_ref="MLOps Spec §3",
        keywords=("model switching", "automatic switching", "promote model", "switching", "how does model switching work"),
    ),
    "automatic_rollback": KnowledgeEntry(
        id="automatic_rollback",
        topic="Automatic Rollback",
        category="MLOps",
        explanation="If an active ML model exhibits degradation (MAE exceeds safety floor or pipeline exceptions occur), the system automatically rolls back to the proven baseline model version to safeguard operational forecasts.",
        allowed_terms=("automatic rollback", "rollback", "safety floor"),
        source_ref="MLOps Spec §4",
        keywords=("rollback", "automatic rollback", "revert model", "safety fallback", "what triggers a rollback", "triggers automatic rollback"),
    ),
    "current_model_display": KnowledgeEntry(
        id="current_model_display",
        topic="Current Model Display",
        category="MLOps",
        explanation="The UI top bar and Assistant footer indicate the active model version string and health state, ensuring complete operational transparency regarding which blend engine generated the forecasts.",
        allowed_terms=("active model", "current model version", "model display"),
        source_ref="PRD §10.1",
        keywords=("current model", "active model display", "which model running"),
    ),

    # 8. Disclaimer & Boundaries
    "decision_support_disclaimer": KnowledgeEntry(
        id="decision_support_disclaimer",
        topic="Decision Support Disclaimer",
        category="Legal",
        explanation="AAGAM is an experimental AI multi-model assimilation platform designed for decision support. It is NOT an official national meteorological warning service; statutory warnings and official bulletins are issued exclusively by the India Meteorological Department (IMD).",
        allowed_terms=("decision support, not an official IMD warning", "IMD authority"),
        source_ref="PRD §1, §9.5",
        keywords=("imd warning", "not an official warning", "disclaimer", "decision support", "why does aagam say decision support"),
    ),
    "system_limitations": KnowledgeEntry(
        id="system_limitations",
        topic="System Limitations",
        category="System",
        explanation="AAGAM is configured for 40 representative Indian stations, provides forecasts up to an 8-day horizon (D0..D7), updates upon regular scheduled NWP ingestion cycles, and strictly never invents current data or substitutes test data into live production answers when live operational forecasts are unavailable.",
        allowed_terms=("limitations", "40 stations", "8-day horizon", "never invent", "no test substitution"),
        source_ref="PRD §4, §5, §9",
        keywords=("limitations", "coverage limits", "what can aagam not do", "scope", "live forecast data is unavailable", "unavailable", "substitute test data", "test data in live answers", "does aagam ever substitute test data"),
    ),
}

_STOPWORDS = {
    "what", "is", "a", "an", "the", "in", "for", "of", "to", "how", "why", "does",
    "do", "and", "or", "on", "are", "by", "can", "with", "when", "all", "about",
}


def find_relevant_knowledge(query: str, max_entries: int = 3) -> List[KnowledgeEntry]:
    """Retrieves relevant authoritative AAGAM knowledge entries for a user query."""
    if not query or not query.strip():
        return []

    q_norm = query.strip().lower().replace("-", " ").replace("_", " ")
    raw_tokens = set(re.findall(r"\b[a-z0-9]+\b", q_norm))
    meaningful_tokens = raw_tokens - _STOPWORDS
    if not meaningful_tokens:
        meaningful_tokens = raw_tokens

    scored: List[tuple[int, KnowledgeEntry]] = []

    for entry in AAGAM_KNOWLEDGE_BASE.values():
        score = 0
        topic_norm = entry.topic.lower().replace("-", " ").replace("_", " ")

        # Exact topic match
        if topic_norm in q_norm or q_norm in topic_norm:
            score += 30

        # Topic tokens overlap
        topic_tokens = set(re.findall(r"\b[a-z0-9]+\b", topic_norm)) - _STOPWORDS
        score += len(meaningful_tokens.intersection(topic_tokens)) * 12

        # Check keyword matches
        for kw in entry.keywords:
            kw_norm = kw.lower().replace("-", " ").replace("_", " ")
            if kw_norm in q_norm or q_norm in kw_norm:
                score += 18
            else:
                kw_tokens = set(re.findall(r"\b[a-z0-9]+\b", kw_norm)) - _STOPWORDS
                score += len(meaningful_tokens.intersection(kw_tokens)) * 6

        # Check allowed terms
        for term in entry.allowed_terms:
            term_norm = term.lower().replace("-", " ").replace("_", " ")
            if term_norm in q_norm:
                score += 15
            else:
                term_tokens = set(re.findall(r"\b[a-z0-9]+\b", term_norm)) - _STOPWORDS
                score += len(meaningful_tokens.intersection(term_tokens)) * 4

        # Explanation token overlap
        exp_tokens = set(re.findall(r"\b[a-z0-9]+\b", entry.explanation.lower())) - _STOPWORDS
        score += len(meaningful_tokens.intersection(exp_tokens)) * 2

        if score > 0:
            scored.append((score, entry))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [entry for _, entry in scored[:max_entries]]


def format_knowledge_context(entries: List[KnowledgeEntry]) -> str:
    """Formats retrieved knowledge entries into a compact, authoritative prompt context."""
    if not entries:
        return ""

    lines = ["AUTHORITATIVE AAGAM SYSTEM KNOWLEDGE:"]
    for e in entries:
        formula_part = f" | Formula: {e.formula}" if e.formula else ""
        lines.append(f"• [{e.topic}] ({e.source_ref}): {e.explanation}{formula_part}")
    lines.append("RULE: Use this authoritative knowledge to explain concepts, metrics, and workflows. For current weather data or numbers, always call tools.")
    return "\n".join(lines)
