"""Hazard Guidance Service (PRD §11.3, Upgrade Pack v1.1 Feature C).

Loads static, team-authored hazard guidance from config/hazard_guidance.yaml.
Strictly deterministic, reviewed editorial copy calibrated to IMD thresholds.
NOT generated by an LLM or external dynamic API.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, Optional

import yaml

logger = logging.getLogger("aagam.api.hazard_guidance")

_GUIDANCE_CACHE: Optional[Dict[str, Any]] = None
_DEFAULT_CONFIG_PATH = Path(__file__).resolve().parents[3] / "config" / "hazard_guidance.yaml"


def load_hazard_guidance(config_path: Optional[Path] = None) -> Dict[str, Any]:
    """Loads and caches hazard guidance from YAML file."""
    global _GUIDANCE_CACHE
    if _GUIDANCE_CACHE is not None and config_path is None:
        return _GUIDANCE_CACHE

    target_path = config_path or _DEFAULT_CONFIG_PATH
    if not target_path.exists():
        logger.warning(f"Hazard guidance file not found at {target_path}")
        return {"guidance": {}, "imd_warning_portal": {}}

    try:
        with open(target_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
            if config_path is None:
                _GUIDANCE_CACHE = data
            return data
    except Exception as exc:
        logger.error(f"Failed to load hazard guidance from {target_path}: {exc}")
        return {"guidance": {}, "imd_warning_portal": {}}


def get_hazard_guidance(hazard: str, severity: str) -> Optional[Dict[str, Any]]:
    """Returns static, team-authored guidance for given hazard and severity.

    Returns:
        Dict with keys: headline, body, precautions (list), official_link, source
        or None if no guidance exists for that hazard/severity.
    """
    data = load_hazard_guidance()
    guidance_map = data.get("guidance", {})
    portal_info = data.get("imd_warning_portal", {})

    hazard_entry = guidance_map.get(hazard)
    if not hazard_entry:
        return None

    sev_entry = hazard_entry.get(severity)
    if not sev_entry:
        return None

    return {
        "hazard": hazard,
        "severity": severity,
        "headline": sev_entry.get("headline", ""),
        "body": sev_entry.get("body", ""),
        "precautions": sev_entry.get("precautions", []),
        "official_link": sev_entry.get("official_link") or portal_info.get("url", "https://mausam.imd.gov.in/responsive/districtWiseWarningGIS.php"),
        "source": portal_info.get("source", "India Meteorological Department (IMD) warning criteria"),
    }
